// Code generated by Wire. DO NOT EDIT.

//go:generate go run -mod=mod github.com/google/wire/cmd/wire
//go:build !wireinject
// +build !wireinject

package main

import (
	"github.com/timhugh/digitalvenue/db/dynamodb"
)

// Injectors from wire.go:

func initializeHandler() (handler, error) {
	mainEventServiceConfig := newEventServiceConfig()
	merchantRepositoryConfig := dynamodb.NewMerchantsRepositoryConfig()
	merchantsRepository, err := dynamodb.NewMerchantsRespository(merchantRepositoryConfig)
	if err != nil {
		return handler{}, err
	}
	mainHandler := newHandler(mainEventServiceConfig, merchantsRepository)
	return mainHandler, nil
}
