AWSTemplateFormatVersion: 2010-09-09

Parameters:
  Image:
    Type: String
    Description: The name of the docker image

Resources:

  ECR:
    Type: AWS::ECR::Repository
    Properties:
      RepositoryName: !Sub 'digitalvenue/${Image}'
      ImageScanningConfiguration:
        scanOnPush: true
      ImageTagMutability: IMMUTABLE
      EmptyOnDelete: true
      RepositoryPolicyText:
        Version: "2012-10-17"
        Statement:
          - Effect: Allow
            Principal:
              Service: lambda.amazonaws.com
            Action:
              - ecr:GetDownloadUrlForLayer
              - ecr:BatchGetImage
              - ecr:BatchCheckLayerAvailability
