AWSTemplateFormatVersion: 2010-09-09

Parameters:
  LambdaGatewayStackName:
    Type: String
    Description: The name of the stack that contains the Lambda API Gateway

Resources:

  LambdaGatewayDeployment:
    Type: AWS::ApiGateway::Deployment
    Properties:
      RestApiId:
        Fn::ImportValue: !Sub '${LambdaGatewayStackName}-LambdaGatewayRestApi'
