AWSTemplateFormatVersion: 2010-09-09

Parameters:
  StackPrefix:
    Type: String
    Description: The prefix for the stack

Resources:

  LambdaGatewayRestApi:
    Type: AWS::ApiGateway::RestApi
    Properties:
      Name: !Sub '${StackPrefix}-lambda-gateway'
      Description: Digital Venue API
      ApiKeySourceType: HEADER
      EndpointConfiguration:
        Types:
          - EDGE

  LambdaGatewayModel:
    Type: AWS::ApiGateway::Model
    Properties:
      ContentType: application/json
      RestApiId: !Ref LambdaGatewayRestApi

  EventsApiResource:
    Type: AWS::ApiGateway::Resource
    Properties:
      ParentId: !GetAtt LambdaGatewayRestApi.RootResourceId
      PathPart: events
      RestApiId: !Ref LambdaGatewayRestApi

Outputs:
  LambdaGatewayRestApi:
    Value: !Ref LambdaGatewayRestApi
    Export:
      Name: !Sub '${StackPrefix}-lambda-gateway-LambdaGatewayRestApi'
  EventsApiResource:
    Value: !Ref EventsApiResource
    Export:
      Name: !Sub '${StackPrefix}-lambda-gateway-EventsApiResource'
