AWSTemplateFormatVersion: 2010-09-09

Parameters:
  LambdaName:
    Type: String
    Description: The name of the lambda (must correspond to the ECR)
  ImageVersion:
    Type: String
    Description: The version of the image to use
  StackPrefix:
    Type: String
    Description: The stack prefix used to reference other stacks
  LogLevel:
    Type: String
    Default: info

Resources:

  Lambda:
    Type: AWS::Lambda::Function
    Properties:
      FunctionName: !Sub '${StackPrefix}-${LambdaName}'
      Code:
        ImageUri:
          Fn::Sub:
            - '${ECRUri}:${ImageVersion}'
            - ECRUri:
                Fn::ImportValue: !Sub "digitalvenue-${LambdaName}-ECRUri"
      PackageType: Image
      Role:
        Fn::ImportValue: !Sub '${StackPrefix}-lambda-role-LambdaRoleArn'
      Architectures:
        - arm64
      Environment:
        Variables:
          WEBHOOK_NOTIFICATION_URL:
            Fn::Sub:
              - '${ApiDomain}/events'
              - ApiDomain:
                  Fn::ImportValue: !Sub '${StackPrefix}-lambda-gateway-ApiDomain'
          LOG_LEVEL: !Ref LogLevel

  LambdaApiPermission:
    Type: AWS::Lambda::Permission
    Properties:
      Action: lambda:InvokeFunction
      FunctionName: !Ref Lambda
      Principal: apigateway.amazonaws.com

Outputs:
  LambdaArn:
    Value: !GetAtt Lambda.Arn
    Export:
      Name: !Sub '${StackPrefix}-${LambdaName}-Arn'
  LambdaRef:
    Value: !Ref Lambda
    Export:
      Name: !Sub '${StackPrefix}-${LambdaName}'
