AWSTemplateFormatVersion: 2010-09-09

Parameters:
  LambdaName:
    Type: String
    Description: The name of the Lambda function

Resources:

  ECR:
    Type: AWS::ECR::Repository
    Properties:
      RepositoryName: !Sub digitalvenue/${LambdaName}
      ImageScanningConfiguration:
        scanOnPush: true
      ImageTagMutability: MUTABLE
      EmptyOnDelete: true
      RepositoryPolicyText:
        Version: "2012-10-17"
        Statement:
          - Effect: Allow
            Principal:
              Service: lambda.amazonaws.com
            Action:
              - ecr:GetDownloadUrlForLayer
              - ecr:BatchGetImage
              - ecr:BatchCheckLayerAvailability

Outputs:
  ECRUri:
    Value: !GetAtt ECR.RepositoryUri
    Export:
      Name: !Sub "digitalvenue-${LambdaName}-ECRUri"
