AWSTemplateFormatVersion: 2010-09-09

Parameters:
  StackPrefix:
    Type: String
    Description: The prefix for the stack
  Environment:
    Type: String
    Description: The environment for the stack
  HostedZoneId:
    Type: String
    Description: The hosted zone id for the domain

Resources:

  LambdaGatewayApi:
    Type: AWS::ApiGatewayV2::Api
    Properties:
      Name: !Sub '${StackPrefix}-lambda-gateway'
      ProtocolType: HTTP

  LambdaGatewayStage:
    Type: AWS::ApiGatewayV2::Stage
    Properties:
      StageName: !Ref Environment
      ApiId: !Ref LambdaGatewayApi
      AutoDeploy: true
      AccessLogSettings:
        Format: '{
                  "httpMethod": "$context.httpMethod",
                  "path": "$context.path",
                  "environment": "$context.stage",
                  "requestId": "$context.requestId",
                  "ip": "$context.identity.sourceIp",
                  "userAgent": "$context.identity.userAgent",
                  "latency": "$context.responseLatency",
                  "httpStatus": "$context.status",
                  "integrationError": "$context.integration.error",
                  "lambdaError": "$context.error.message"
        }'
        DestinationArn: !GetAtt LambdaGatewayApiLogGroup.Arn

  DomainName:
    Type: AWS::ApiGatewayV2::DomainName
    Properties:
      DomainName: !Sub 'api.${Environment}.digital-venue.net'
      DomainNameConfigurations:
        - EndpointType: REGIONAL
          CertificateArn:
            Fn::ImportValue: !Sub '${StackPrefix}-domain-certificate-arn'
          SecurityPolicy: TLS_1_2

  ApiMapping:
    Type: AWS::ApiGatewayV2::ApiMapping
    Properties:
      DomainName: !Ref DomainName
      ApiId: !Ref LambdaGatewayApi
      Stage: !Ref LambdaGatewayStage

  DnsRecordSet:
    Type: AWS::Route53::RecordSet
    Properties:
      HostedZoneId: !Ref HostedZoneId
      Name: !Sub 'api.${Environment}.digital-venue.net'
      Type: A
      AliasTarget:
        DNSName: !GetAtt DomainName.RegionalDomainName
        HostedZoneId: !GetAtt DomainName.RegionalHostedZoneId

  LambdaGatewayApiLogGroup:
    Type: AWS::Logs::LogGroup
    Properties:
      LogGroupName: !Sub '/aws/api-gateway/api-logs-${Environment}'

Outputs:
  ApiDomain:
    Value: !Sub 'api.${Environment}.digital-venue.net'
    Export:
      Name: !Sub '${StackPrefix}-lambda-gateway-ApiDomain'
  LambdaGatewayApi:
    Value: !Ref LambdaGatewayApi
    Export:
      Name: !Sub '${StackPrefix}-lambda-gateway-LambdaGatewayApi'
