variables:
  AWS_DEFAULT_REGION:
    value: "us-west-2"
    description: "AWS region to deploy to"
  DOCKER_REGISTRY: $AWS_ACCOUNT_ID.dkr.ecr.$AWS_DEFAULT_REGION.amazonaws.com

default:
  image: registry.gitlab.com/timhugh/digitalvenue/gitlab-runner:latest
  services:
    - docker:stable-dind
  before_script:
    - docker buildx create --use --name container --driver=docker-container
    # configure awscli credentials
    - aws configure set aws_access_key_id $AWS_ACCESS_KEY_ID
    - aws configure set aws_secret_access_key $AWS_SECRET_ACCESS_KEY
    - aws configure set region $AWS_DEFAULT_REGION
    # configure ECR login for docker
    - aws ecr get-login-password --region $AWS_DEFAULT_REGION | docker login --username AWS --password-stdin $DOCKER_REGISTRY

stages:
  - build
  - staging
  - production

base-images:
  stage: build
  parallel:
    matrix:
      - IMAGE: [ builder-base, runtime-base ]
  script:
    - aws cloudformation deploy --no-fail-on-empty-changeset --template-file .cloudformation/base-ecr.yml --stack-name digitalvenue-$IMAGE-ecr --parameter-overrides Image=$IMAGE
    - .ci/build-image $DOCKER_REGISTRY $IMAGE $CI_COMMIT_SHA docker/$IMAGE.Dockerfile

infra:
  parallel:
    matrix:
      - DEPLOY_ENVIRONMENT: [ staging, production ]
  variables:
    STACK_PREFIX: digitalvenue-$DEPLOY_ENVIRONMENT
  stage: build
  script:
    - aws cloudformation deploy --no-fail-on-empty-changeset --template-file .cloudformation/lambda-role.yml --stack-name $STACK_PREFIX-lambda-role --capabilities CAPABILITY_IAM --parameter-overrides StackPrefix=$STACK_PREFIX
    - aws cloudformation deploy --no-fail-on-empty-changeset --template-file .cloudformation/certificate.yml --stack-name $STACK_PREFIX-certificate --parameter-overrides StackPrefix=$STACK_PREFIX HostedZoneId=$ROUTE_53_HOSTED_ZONE_ID Environment=$DEPLOY_ENVIRONMENT
    - aws cloudformation deploy --no-fail-on-empty-changeset --template-file .cloudformation/lambda-gateway.yml --stack-name $STACK_PREFIX-lambda-gateway --parameter-overrides StackPrefix=$STACK_PREFIX Environment=$DEPLOY_ENVIRONMENT HostedZoneId=$ROUTE_53_HOSTED_ZONE_ID

build:
  stage: build
  needs: [ "base-images", "infra" ]
  variables:
    BUILDER_IMAGE: $DOCKER_REGISTRY/digitalvenue/builder-base:$CI_COMMIT_SHA
  script:
    - aws cloudformation deploy --no-fail-on-empty-changeset --template-file .cloudformation/base-ecr.yml --stack-name digitalvenue-lambda-build-ecr --parameter-overrides Image=lambda-build
    - .ci/build-image $DOCKER_REGISTRY lambda-build $CI_COMMIT_SHA docker/lambda-build.Dockerfile "--build-arg BUILD=$BUILDER_IMAGE"

build-lambdas:
  stage: build
  needs: [ "build" ]
  parallel:
    matrix:
      - LAMBDA_NAME: [ lambda-test, webhook-events ]
  rules:
    - if: '$LABMDA_NAME == "webhook-events"'
      variables:
        ENVIRONMENT_VARIABLES: ""
    - when: always
      variables:
        ENVIRONMENT_VARIABLES: ""
  variables:
    BUILDER_IMAGE: $DOCKER_REGISTRY/digitalvenue/lambda-build:$CI_COMMIT_SHA
    RUNTIME_BASE_IMAGE: $DOCKER_REGISTRY/digitalvenue/runtime-base:$CI_COMMIT_SHA
  script:
    - aws cloudformation deploy --no-fail-on-empty-changeset --template-file .cloudformation/lambda-ecr.yml --stack-name digitalvenue-$LAMBDA_NAME-ecr --parameter-overrides LambdaName=$LAMBDA_NAME $ENVIRONMENT_VARIABLES
    - .ci/build-image $DOCKER_REGISTRY $LAMBDA_NAME $CI_COMMIT_SHA docker/lambda-runtime.Dockerfile "--build-arg BUILD=$BUILDER_IMAGE --build-arg RUNTIME=$RUNTIME_BASE_IMAGE --build-arg LAMBDA=$LAMBDA_NAME"

.deploy-lambdas:
  needs: [ "build-lambdas" ]
  parallel:
    matrix:
      - LAMBDA_NAME: [ lambda-test, webhook-events ]
  variables:
    STACK_PREFIX: digitalvenue-$DEPLOY_ENVIRONMENT
  script:
    - aws cloudformation deploy --no-fail-on-empty-changeset --template-file .cloudformation/lambda.yml --stack-name $STACK_PREFIX-$LAMBDA_NAME --parameter-overrides StackPrefix=$STACK_PREFIX LambdaName=$LAMBDA_NAME ImageVersion=$CI_COMMIT_SHA
    - aws cloudformation deploy --no-fail-on-empty-changeset --template-file $LAMBDA_NAME/api.yml --stack-name $STACK_PREFIX-$LAMBDA_NAME-api --parameter-overrides StackPrefix=$STACK_PREFIX LambdaName=$LAMBDA_NAME

deploy-lambdas-staging:
  stage: staging
  extends: .deploy-lambdas
  variables:
    DEPLOY_ENVIRONMENT: staging

deploy-lambdas-production:
  stage: production
  when: manual
  extends: .deploy-lambdas
  variables:
    DEPLOY_ENVIRONMENT: production
