services:
  aws-localstack:
    container_name: "${LOCALSTACK_DOCKER_NAME:-localstack-main}"
    image: localstack/localstack-pro
    ports:
      - "127.0.0.1:4566:4566"
      - "127.0.0.1:4510-4559:4510-4559"
    environment:
      LOCALSTACK_AUTH_TOKEN: ${LOCALSTACK_AUTH_TOKEN}
    volumes:
      - "./.docker/localstack/:/var/lib/localstack"
      - "/var/run/docker.sock:/var/run/docker.sock"

  http-gateway:
    image: nginx:latest
    container_name: http-gateway
    ports:
      - "8080:80"
    volumes:
      - ./.docker/http-gateway/nginx.conf:/etc/nginx/conf.d/default.conf
    depends_on:
      - square-events
      - square-event-gatherer
      - ticket-generator

  mailcatcher:
    image: schickling/mailcatcher:latest
    ports:
      - "1080:1080"
      - "1025:1025"

  square-events:
    build:
      context: .
      dockerfile: .docker/function.Dockerfile
    container_name: square-events
    command: [ "go", "run", "./functions/square-events" ]
    volumes:
      - .:/digitalvenue:ro
    environment:
      LOCAL_AWS_URL: ${LOCAL_AWS_URL}
      CORE_DATA_TABLE_NAME: ${CORE_DATA_TABLE_NAME}
      SQUARE_WEBHOOK_NOTIFICATION_URL: ${SQUARE_WEBHOOK_NOTIFICATION_URL}
      LOG_LEVEL: debug
      ENVIRONMENT: dev

  square-event-gatherer:
    build:
      context: .
      dockerfile: .docker/function.Dockerfile
    container_name: square-event-gatherer
    command: [ "go", "run", "./functions/square-event-gatherer" ]
    volumes:
      - .:/digitalvenue:ro
    environment:
      LOCAL_AWS_URL: ${LOCAL_AWS_URL}
      CORE_DATA_TABLE_NAME: ${CORE_DATA_TABLE_NAME}
      LOG_LEVEL: debug
      ENVIRONMENT: dev

  ticket-generator:
    build:
      context: .
      dockerfile: .docker/function.Dockerfile
    container_name: ticket-generator
    command: [ "go", "run", "./functions/ticket-generator" ]
    volumes:
      - .:/digitalvenue:ro
    environment:
      LOCAL_AWS_URL: ${LOCAL_AWS_URL}
      CORE_DATA_TABLE_NAME: ${CORE_DATA_TABLE_NAME}
      S3_QR_CODE_BUCKET_NAME: ${S3_QR_CODE_BUCKET_NAME}
      LOG_LEVEL: debug
      ENVIRONMENT: dev

  ticket-mailer:
    build:
      context: .
      dockerfile: .docker/function.Dockerfile
    container_name: ticket-mailer
    command: [ "go", "run", "./functions/ticket-mailer" ]
    volumes:
      - .:/digitalvenue:ro
    environment:
      LOCAL_AWS_URL: ${LOCAL_AWS_URL}
      CORE_DATA_TABLE_NAME: ${CORE_DATA_TABLE_NAME}
      LOG_LEVEL: debug
      ENVIRONMENT: dev
