version = 0.1
[prod.deploy.parameters]
stack_name = "digitalvenue-prod"
resolve_s3 = true
s3_prefix = "digitalvenue-prod"
region = "us-west-2"
confirm_changeset = true
capabilities = "CAPABILITY_IAM"
resolve_image_repos = true
