Transform: AWS::Serverless-2016-10-31

Parameters:
  BuilderVersion:
    Type: String
  AwsRegion:
    Type: String
  AwsAccountId:
    Type: String

Resources:
  TestLambda:
    Type: AWS::Serverless::Function
    FunctionName: testLambda
    Properties:
      PackageType: Image
      Architectures:
        - arm64
      Events:
        Api:
          Type: Api
          Properties:
            Path: /test
            Method: get
    Metadata:
      Dockerfile: Dockerfile
      DockerContext: lambda-test
      DockerTag: !Sub ${Version}
      DockerBuildArgs:
        BUILDER: !Sub ${AwsAccountId}.dkr.ecr.${AwsRegion}.amazonaws.com/digitalvenue-builder:${BuilderVersion}
