AWSTemplateFormatVersion: 2010-09-09

Parameters:
  StackPrefix:
    Type: String
    Description: The prefix to use for the stack names

Resources:

  TestLambdaApiIntegration:
    Type: AWS::ApiGatewayV2::Integration
    Properties:
      ApiId:
        Fn::ImportValue: !Sub '${StackPrefix}-lambda-gateway-LambdaGatewayApi'
      IntegrationType: AWS_PROXY
      IntegrationMethod: POST
      IntegrationUri:
        Fn::Sub:
          - arn:aws:apigateway:${AWS::Region}:lambda:path/2015-03-31/functions/${LambdaArn}/invocations
          - LambdaArn:
              Fn::ImportValue: !Sub '${StackPrefix}-lambda-test-Arn'
      PayloadFormatVersion: "1.0"

  TestLambdaApiRoute:
    Type: AWS::ApiGatewayV2::Route
    Properties:
      ApiId:
        Fn::ImportValue: !Sub '${StackPrefix}-lambda-gateway-LambdaGatewayApi'
      RouteKey: 'POST /test'
      Target: !Sub 'integrations/${TestLambdaApiIntegration}'
