AWSTemplateFormatVersion: 2010-09-09

Parameters:
  LambdaTestECRStackName:
    Type: String
    Description: The name of the stack that contains the LambdaTest ECR
  LambdaRoleStackName:
    Type: String
    Description: The name of the stack that contains the LambdaRole
  ImageVersion:
    Type: String
    Description: The version of the image to use

Resources:

  LambdaTest:
    Type: AWS::Lambda::Function
    Properties:
      FunctionName: lambdaTest
      Code:
        ImageUri:
          Fn::Sub:
            - '${LambdaTestECRUri}:${ImageVersion}'
            - LambdaTestECRUri:
                Fn::ImportValue: !Sub '${LambdaTestECRStackName}-LambdaTestECRUri'
      PackageType: Image
      Role:
        Fn::ImportValue: !Sub '${LambdaRoleStackName}-LambdaRoleArn'
      Architectures:
        - arm64
      Timeout: 30

Outputs:
  LambdaTestArn:
    Value: !GetAtt LambdaTest.Arn
    Export:
      Name: !Sub '${AWS::StackName}-LambdaTestArn'
  LambdaTest:
    Value: !Ref LambdaTest
    Export:
      Name: !Sub '${AWS::StackName}-LambdaTest'
