server {
 listen 80;
   location /events {
     proxy_pass http://square-events:8080/2015-03-31/functions/function/invocations;
   }
   location /invoke/square-event-gatherer {
     proxy_pass http://square-event-gatherer:8080/2015-03-31/functions/function/invocations;
   }
}
