-- Up
CREATE TABLE IF NOT EXISTS versions (
  version INTEGER PRIMARY KEY,
  name TEXT NOT NULL,
  applied_at DATETIME NOT NULL DEFAULT CURRENT_TIMESTAMP,
  status TEXT NOT NULL DEFAULT 'pending'
);

-- Down
DROP TABLE versions;
