name: builder-image

env:
  AWS_ACCOUNT_ID: ${{ secrets.AWS_ACCOUNT_ID }}
  AWS_ACCESS_KEY_ID: ${{ secrets.AWS_ACCESS_KEY_ID }}
  AWS_SECRET_ACCESS_KEY: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
  AWS_DEFAULT_REGION: us-west-2

on:
  push:
    paths:
      - docker/builder-version
  workflow_dispatch:

jobs:
  builderImage:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4

      - run: echo "BUILDER_VERSION=$(cat docker/builder-version.txt)" >> $GITHUB_ENV
      - run: echo "IMAGE=${{ env.AWS_ACCOUNT_ID }}.dkr.ecr.${{ env.AWS_DEFAULT_REGION }}.amazonaws.com/digitalvenue/builder:${{ env.BUILDER_VERSION }}" >> $GITHUB_ENV

      - uses: aws-actions/configure-aws-credentials@v4
        with:
          aws-access-key-id: ${{ env.AWS_ACCESS_KEY_ID }}
          aws-secret-access-key: ${{ env.AWS_SECRET_ACCESS_KEY }}
          aws-region: ${{ env.AWS_DEFAULT_REGION }}

      - run: aws cloudformation deploy --template-file .cloudformation/builder-ecr.yml --stack-name digitalvenue-builder-ecr

      - uses: aws-actions/amazon-ecr-login@v2

      - uses: docker/setup-buildx-action@v3

      - uses: docker/build-push-action@v5
        with:
          context: .
          file: docker/builder.Dockerfile
          platforms: linux/arm64
          push: true
          tags: ${{ env.IMAGE }}
          provenance: false
