env:
  AWS_ACCOUNT_ID: ${{ secrets.AWS_ACCOUNT_ID }}
  AWS_ACCESS_KEY_ID: ${{ secrets.AWS_ACCESS_KEY_ID }}
  AWS_SECRET_ACCESS_KEY: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
  AWS_DEFAULT_REGION: us-west-2

on:
  workflow_dispatch:
    inputs:
      environment:
        description: 'Environment to deploy to'
        required: true
        type: choice
        options:
          - prod
          - stage
          - dev
      lambda:
        description: 'Lambda to deploy'
        required: true
      build:
        description: 'Build to deploy'
        required: true
        default: 'latest'

jobs:
  deployLambda:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v4

      - run: echo "LAMBDA=${{ github.event.inputs.lambda }}" >> $GITHUB_ENV
      - run: echo "VERSION=${{ github.event.inputs.build }}" >> $GITHUB_ENV
      - run: echo "BUILD_IMAGE=${{ env.AWS_ACCOUNT_ID }}.dkr.ecr.${{ env.AWS_DEFAULT_REGION }}.amazonaws.com/digitalvenue/lambda-build:${{ env.VERSION }}" >> $GITHUB_ENV
      - run: echo "RUNTIME_BASE_IMAGE=${{ env.AWS_ACCOUNT_ID }}.dkr.ecr.${{ env.AWS_DEFAULT_REGION }}.amazonaws.com/digitalvenue/runtime-base:latest" >> $GITHUB_ENV
      - run: echo "LAMBDA_IMAGE=${{ env.AWS_ACCOUNT_ID }}.dkr.ecr.${{ env.AWS_DEFAULT_REGION }}.amazonaws.com/digitalvenue/${{ env.LAMBDA }}:${{ github.sha }}" >> $GITHUB_ENV
      - run: echo "STACK_PREFIX=digitalvenue-${{ github.event.inputs.environment }}" >> $GITHUB_ENV

      - uses: aws-actions/configure-aws-credentials@v4
        with:
          aws-access-key-id: ${{ env.AWS_ACCESS_KEY_ID }}
          aws-secret-access-key: ${{ env.AWS_SECRET_ACCESS_KEY }}
          aws-region: ${{ env.AWS_DEFAULT_REGION }}

      - name: deploy ${{ env.LAMBDA }} ECR
        run: aws cloudformation deploy --template-file .cloudformation/lambda-ecr.yml --stack-name digitalvenue-${{ env.LAMBDA }}-ecr --parameter-overrides LambdaName=${{ env.LAMBDA }}

      - uses: docker/setup-buildx-action@v3

      - uses: aws-actions/amazon-ecr-login@v2

      - run: docker buildx build --push --provenance false --platform linux/arm64 -t ${{ env.LAMBDA_IMAGE }} --build-arg BUILD=${{ env.BUILD_IMAGE }} --build-arg RUNTIME=${{ env.RUNTIME_BASE_IMAGE }} --build-arg LAMBDA=${{ env.LAMBDA }} --file docker/lambda-runtime.Dockerfile .

      - name: deploy ${{ env.LAMBDA }} lambda
        run: aws cloudformation deploy --template-file .cloudformation/lambda.yml --stack-name ${{ env.STACK_PREFIX }}-${{ env.LAMBDA}} --parameter-overrides StackPrefix=${{ env.STACK_PREFIX }} LambdaName=${{ env.LAMBDA }} ImageVersion=${{ github.sha }}

      - name: deploy ${{ env.LAMBDA }} api
        run: aws cloudformation deploy --template-file ${{ env.LAMBDA }}/api.yml --stack-name ${{ env.STACK_PREFIX }}-${{ env.LAMBDA}}-api --parameter-overrides StackPrefix=${{ env.STACK_PREFIX }} LambdaName=${{ env.LAMBDA }}