name: deploy-env

env:
  AWS_ACCOUNT_ID: ${{ secrets.AWS_ACCOUNT_ID }}
  AWS_ACCESS_KEY_ID: ${{ secrets.AWS_ACCESS_KEY_ID }}
  AWS_SECRET_ACCESS_KEY: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
  AWS_DEFAULT_REGION: us-west-2

on:
  workflow_dispatch:
    inputs:
      environment:
        description: 'Environment to deploy to'
        required: true
        type: choice
        options:
          - prod
          - stage
          - dev

jobs:
  baseImages:
    strategy:
      matrix:
        image:
          - build
          - runtime

    name: build and push ${{ matrix.image }} image
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
        with:
          fetch-depth: 2

      - run: echo "IMAGE=${{ env.AWS_ACCOUNT_ID }}.dkr.ecr.${{ env.AWS_DEFAULT_REGION }}.amazonaws.com/digitalvenue/${{ matrix.image }}" >> $GITHUB_ENV

      - uses: aws-actions/configure-aws-credentials@v4
        with:
          aws-access-key-id: ${{ env.AWS_ACCESS_KEY_ID }}
          aws-secret-access-key: ${{ env.AWS_SECRET_ACCESS_KEY }}
          aws-region: ${{ env.AWS_DEFAULT_REGION }}

      - run: aws cloudformation deploy --template-file .cloudformation/base-ecr.yml --stack-name digitalvenue-${{ matrix.image }}-ecr --parameter-overrides Image=${{ matrix.image }}

      - uses: aws-actions/amazon-ecr-login@v2

      - uses: docker/setup-buildx-action@v3

      # All images are tagged with the current SHA, but we use the latest tag for build caching
      - name: push ${{ env.IMAGE }}:latest
        run: docker buildx build --push --provenance false --platform linux/arm64 -t ${{ env.IMAGE }}:latest --build-arg BUILDKIT_INLINE_CACHE=1 --cache-from "type=registry,ref=${{ env.IMAGE }}:latest-cache" --cache-to "mode=max,image-manifest=true,oci-mediatypes=true,type=registry,ref=${{ env.IMAGE }}:latest-cache" --file docker/${{ matrix.image }}.Dockerfile .
      - name: push ${{ env.IMAGE }}:${{ github.sha }}
        run: docker buildx build --push --provenance false --platform linux/arm64 -t ${{ env.IMAGE }}:${{ github.sha }} --build-arg BUILDKIT_INLINE_CACHE=1 --cache-from "type=registry,ref=${{ env.IMAGE }}:latest-cache" --file docker/${{ matrix.image }}.Dockerfile .

  buildAndDeployInfra:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v4

      - run: echo "STACK_PREFIX=digitalvenue-${{ github.event.inputs.environment }}" >> $GITHUB_ENV

      - uses: aws-actions/configure-aws-credentials@v4
        with:
          aws-access-key-id: ${{ env.AWS_ACCESS_KEY_ID }}
          aws-secret-access-key: ${{ env.AWS_SECRET_ACCESS_KEY }}
          aws-region: ${{ env.AWS_DEFAULT_REGION }}

      - name: deploy lambda IAM role
        run: aws cloudformation deploy --template-file .cloudformation/lambda-role.yml --stack-name ${{ env.STACK_PREFIX }}-lambda-role --capabilities CAPABILITY_IAM --parameter-overrides StackPrefix=${{ env.STACK_PREFIX }}

      - name: deploy lambda api gateway
        run: aws cloudformation deploy --template-file .cloudformation/lambda-gateway.yml --stack-name ${{ env.STACK_PREFIX }}-lambda-gateway --parameter-overrides StackPrefix=${{ env.STACK_PREFIX }}

  buildAndDeployLambdas:
    needs: [baseImages, buildAndDeployInfra]

    strategy:
      matrix:
        lambdas:
          - lambda-test

    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v4

      # TODO: get builder and runner versions for this specific lambda
      - run: echo "BUILDER_IMAGE=${{ env.AWS_ACCOUNT_ID }}.dkr.ecr.${{ env.AWS_DEFAULT_REGION }}.amazonaws.com/digitalvenue/build:${{ github.sha }}" >> $GITHUB_ENV
      - run: echo "RUNNER_IMAGE=${{ env.AWS_ACCOUNT_ID }}.dkr.ecr.${{ env.AWS_DEFAULT_REGION }}.amazonaws.com/digitalvenue/runtime:${{ github.sha }}" >> $GITHUB_ENV
      - run: echo "LAMBDA_IMAGE=${{ env.AWS_ACCOUNT_ID }}.dkr.ecr.${{ env.AWS_DEFAULT_REGION }}.amazonaws.com/digitalvenue/${{ matrix.lambdas }}:${{ github.sha }}" >> $GITHUB_ENV
      - run: echo "STACK_PREFIX=digitalvenue-${{ github.event.inputs.environment }}" >> $GITHUB_ENV

      - uses: aws-actions/configure-aws-credentials@v4
        with:
          aws-access-key-id: ${{ env.AWS_ACCESS_KEY_ID }}
          aws-secret-access-key: ${{ env.AWS_SECRET_ACCESS_KEY }}
          aws-region: ${{ env.AWS_DEFAULT_REGION }}

      - name: deploy ${{ matrix.lambdas }} ECR
        run: aws cloudformation deploy --template-file .cloudformation/lambda-ecr.yml --stack-name digitalvenue-${{ matrix.lambdas}}-ecr --parameter-overrides LambdaName=${{ matrix.lambdas }}

      - uses: docker/setup-buildx-action@v3

      - uses: aws-actions/amazon-ecr-login@v2

      - run: docker buildx build --push --provenance false --platform linux/arm64 -t ${{ env.LAMBDA_IMAGE }} --build-arg BUILD=${{ env.BUILDER_IMAGE }} --build-arg RUNTIME=${{ env.RUNNER_IMAGE }} --build-arg LAMBDA=${{ matrix.lambdas }} --file docker/lambda.Dockerfile .

      - name: deploy ${{ matrix.lambdas }} lambda
        run: aws cloudformation deploy --template-file .cloudformation/lambda.yml --stack-name ${{ env.STACK_PREFIX }}-${{ matrix.lambdas}} --parameter-overrides StackPrefix=${{ env.STACK_PREFIX }} LambdaName=${{ matrix.lambdas }} ImageVersion=${{ github.sha }}

      - name: deploy ${{ matrix.lambdas }} api
        run: aws cloudformation deploy --template-file .cloudformation/lambda-api.yml --stack-name ${{ env.STACK_PREFIX }}-${{ matrix.lambdas}}-api --parameter-overrides StackPrefix=${{ env.STACK_PREFIX }} LambdaName=${{ matrix.lambdas }}

  deployApiGateway:
    needs: [ buildAndDeployInfra, buildAndDeployLambdas ]

    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v4

      - run: echo "STACK_PREFIX=digitalvenue-${{ github.event.inputs.environment }}" >> $GITHUB_ENV

      - uses: aws-actions/configure-aws-credentials@v4
        with:
          aws-access-key-id: ${{ env.AWS_ACCESS_KEY_ID }}
          aws-secret-access-key: ${{ env.AWS_SECRET_ACCESS_KEY }}
          aws-region: ${{ env.AWS_DEFAULT_REGION }}

      - name: deploy api gateway
        run: aws cloudformation deploy --template-file .cloudformation/lambda-gateway-deployment.yml --stack-name ${{ env.STACK_PREFIX }}-lambda-gateway-deployment --parameter-overrides StackPrefix=${{ env.STACK_PREFIX }}
