name: Deploy
run-name: Deploying ${{github.head_ref}}

on:
  workflow_run:
    workflows: ["Build and test"]
    types: [completed]
    branches: [main]

jobs:
  dv-test:
    runs-on: ubuntu-latest
    steps:
      - name: Configure aws
        uses: aws-actions/configure-aws-credentials@v4
        with:
          aws-access-key-id: ${{ secrets.AWS_ACCESS_KEY }}
          aws-secret-access-key: ${{ secrets.AWS_SECRET_KEY }}
          aws-region: us-west-2

      - name: Download build
        uses: actions/download-artifact@v4
        with:
          name: lambda-test-${{github.sha}}.zip

      - name: Deploy to AWS Lambda
        run: aws lambda update-function-code --function-name dv-test-function --zip-file fileb://lambda-test-${{github.sha}}.zip
