name: prod-deploy

env:
  AWS_ACCOUNT_ID: ${{ secrets.AWS_ACCOUNT_ID }}
  AWS_ACCESS_KEY_ID: ${{ secrets.AWS_ACCESS_KEY_ID }}
  AWS_SECRET_ACCESS_KEY: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
  AWS_DEFAULT_REGION: us-west-2

on:
  workflow_dispatch:
    inputs:
      environment:
        description: 'Environment to deploy to'
        required: true
        type: choice
        options:
          - prod
          - stage
          - dev

jobs:
  buildAndDeployInfra:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v4

      - run: echo "STACK_PREFIX=digitalvenue-${{ github.event.inputs.environment }}" >> $GITHUB_ENV

      - uses: aws-actions/configure-aws-credentials@v4
        with:
          aws-access-key-id: ${{ env.AWS_ACCESS_KEY_ID }}
          aws-secret-access-key: ${{ env.AWS_SECRET_ACCESS_KEY }}
          aws-region: ${{ env.AWS_DEFAULT_REGION }}

      - name: deploy lambda IAM role
        run: aws cloudformation deploy --template-file .cloudformation/lambda-role.yml --stack-name ${{ env.STACK_PREFIX }}-lambda-role --capabilities CAPABILITY_IAM

      - name: deploy lambda api gateway
        run: aws cloudformation deploy --template-file .cloudformation/lambda-gateway.yml --stack-name ${{ env.STACK_PREFIX }}-lambda-gateway

  buildAndDeployLambdas:
    needs: buildAndDeployInfra

    strategy:
      matrix:
        lambdas:
          - lambda-test

    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v4

      # TODO: get builder version for this specific lambda
      - run: echo "BUILDER_VERSION=$(cat docker/builder-version.txt)" >> $GITHUB_ENV
      - run: echo "BUILDER_IMAGE=${{ env.AWS_ACCOUNT_ID }}.dkr.ecr.${{ env.AWS_DEFAULT_REGION }}.amazonaws.com/digitalvenue/builder:${{ env.BUILDER_VERSION }}" >> $GITHUB_ENV
      - run: echo "LAMBDA_IMAGE=${{ env.AWS_ACCOUNT_ID }}.dkr.ecr.${{ env.AWS_DEFAULT_REGION }}.amazonaws.com/digitalvenue/${{ matrix.lambdas }}:${{ github.sha }}" >> $GITHUB_ENV
      - run: echo "STACK_PREFIX=digitalvenue-${{ github.event.inputs.environment }}" >> $GITHUB_ENV

      - uses: aws-actions/configure-aws-credentials@v4
        with:
          aws-access-key-id: ${{ env.AWS_ACCESS_KEY_ID }}
          aws-secret-access-key: ${{ env.AWS_SECRET_ACCESS_KEY }}
          aws-region: ${{ env.AWS_DEFAULT_REGION }}

      - name: deploy ${{ matrix.lambdas }} ECR
        run: aws cloudformation deploy --template-file ${{ matrix.lambdas }}/ecr.yml --stack-name digitalvenue-${{ matrix.lambdas}}-ecr

      - uses: docker/setup-buildx-action@v3

      - uses: aws-actions/amazon-ecr-login@v2

      - uses: docker/build-push-action@v5
        with:
          context: ${{ matrix.lambdas }}
          file: ${{ matrix.lambdas }}/Dockerfile
          platforms: linux/arm64
          push: true
          tags: ${{ env.LAMBDA_IMAGE }}
          build-args: BUILDER=${{ env.BUILDER_IMAGE }}
          provenance: false

      - name: deploy ${{ matrix.lambdas }} lambda
        run: aws cloudformation deploy --template-file ${{ matrix.lambdas }}/lambda.yml --stack-name ${{ env.STACK_PREFIX }}-${{ matrix.lambdas}} --parameter-overrides LambdaTestECRStackName=digitalvenue-${{ matrix.lambdas}}-ecr LambdaRoleStackName=${{ env.STACK_PREFIX }}-lambda-role ImageVersion=${{ github.sha }}

      - name: deploy ${{ matrix.lambdas }} api
        run: aws cloudformation deploy --template-file ${{matrix.lambdas }}/api.yml --stack-name ${{ env.STACK_PREFIX }}-${{ matrix.lambdas}}-api --parameter-overrides LambdaTestStackName=${{ env.STACK_PREFIX }}-${{ matrix.lambdas}} LambdaGatewayStackName=${{ env.STACK_PREFIX }}-lambda-gateway

  deployApiGateway:
    needs: [ buildAndDeployInfra, buildAndDeployLambdas ]

    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v4

      - run: echo "STACK_PREFIX=digitalvenue-${{ github.event.inputs.environment }}" >> $GITHUB_ENV

      - uses: aws-actions/configure-aws-credentials@v4
        with:
          aws-access-key-id: ${{ env.AWS_ACCESS_KEY_ID }}
          aws-secret-access-key: ${{ env.AWS_SECRET_ACCESS_KEY }}
          aws-region: ${{ env.AWS_DEFAULT_REGION }}

      - name: deploy api gateway
        run: aws cloudformation deploy --template-file .cloudformation/lambda-gateway-deployment.yml --stack-name ${{ env.STACK_PREFIX }}-lambda-gateway-deployment --parameter-overrides LambdaGatewayStackName=${{ env.STACK_PREFIX }}-lambda-gateway
